---
- name: installing python 2 pip for ansible
  package:
    name: python-pip
    state: present
  become: true

- name: install dependency
  pip:
    name: docker-py
  become: true

- name: Create mqtt config directory
  file:
    path: /srv/mqtt/config/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create mqtt data directory
  file:
    path: /srv/mqtt/data/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create mqtt log directory
  file:
    path: /srv/mqtt/log/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create OpenRace log directory
  file:
    path: /srv/openrace/log/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create OpenRace race archive directory
  file:
    path: /srv/openrace/archive/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: create empty mqtt users file
  copy:
    src: mqtt-users.txt
    dest: /srv/mqtt/data/mqtt-users.txt
  changed_when: false

- name: run mqtt container
  docker_container:
    name: 'mqtt'
    image: 'eclipse-mosquitto'
    state: 'started'
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
     - "/srv/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
     - "/srv/mqtt/log:/mosquitto/log:rw"
     - "/srv/mqtt/data:/mosquitto/data:rw"

- name: creating mqtt user
  shell: docker exec -d mqtt /usr/bin/mosquitto_passwd -b /mosquitto/data/mqtt-users.txt {{ mqtt.user }} {{ mqtt.pass }}
  changed_when: false
