---
- name: installing python 2 pip for ansible
  package:
    name: python-pip
    state: present
  become: true

- name: install dependency
  pip:
    name: docker-py
  become: true

- name: Create mqtt config directory
  file:
    path: /srv/mqtt/config/
    state: directory
    owner: pi
    group: pi
    mode: 0775
  become: true

- name: Create mqtt data directory
  file:
    path: /srv/mqtt/data/
    state: directory
    owner: pi
    group: pi
    mode: 0775
  become: true

- name: Create mqtt log directory
  file:
    path: /srv/mqtt/log/
    state: directory
    owner: pi
    group: pi
    mode: 0775
  become: true

- name: Run MQTT container
  docker_container:
    name: 'mqtt'
    image: 'pascaldevink/rpi-mosquitto'
    state: 'started'
    user: 'pi'
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
     - "/srv/mqtt/config:/mqtt/config:ro"
     - "/srv/mqtt/log:/mqtt/log:rw"
     - "/srv/mqtt/data:/mqtt/data:rw"
