---
- name: Create race_core image
  docker_image:
    name: race_core
    path: "{{ playbook_dir }}/../src/race_core"
    force: yes
  become: true
  tags:
     - core

- name: Create led_control image
  docker_image:
    name: led_control
    path: "{{ playbook_dir }}/../src/led_control"
    force: yes
  become: true
  tags:
     - led

- name: Create audio_output image
  docker_image:
    name: audio_output
    path: "{{ playbook_dir }}/../src/audio_output"
    force: yes
  become: true
  tags:
     - led
