---

- name: selecting self built images
  set_fact:
   ui_image: "openrace/ui:{{ openrace.version }}"
   led_control_image: led_control
   race_core_image: race_core
  when: openrace.build_images

- name: "selecting dockerhub images with version {{ openrace.version }}"
  set_fact:
   ui_image: "openrace/ui:{{ openrace.version }}"
   led_control_image: "openrace/led_control:{{ openrace.version }}"
   race_core_image: "openrace/race_core:{{ openrace.version }}"
  when: not openrace.build_images

- name: "Create ui container from {{ ui_image }}"
  docker_container:
    name: ui
    image: "{{ ui_image }}"
    recreate: yes
    restart_policy: "{{ openrace.restart_policy }}"
    networks:
      - name: openrace
    ports:
      "80:80"
    env:
      MQTT_WEBSOCKETS_HOST: mqtt:9001
  become: true
  tags:
     - ui

- name: Create OpenRace log directory
  file:
    path: /srv/openrace/log/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create OpenRace race archive directory
  file:
    path: /srv/openrace/archive/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: "Create led_control container from {{ led_control_image }}"
  docker_container:
    name: led_control
    image: "{{ led_control_image }}"
    recreate: yes
    restart_policy: "{{ openrace.restart_policy }}"
    networks:
      - name: openrace
    volumes:
      - "/srv/openrace/log:/app/log/:rw"
    env:
      MQTT_HOST: mqtt
      MQTT_USER: openrace
      MQTT_PASS: PASSWORD
      DEBUG: "false"
  become: true

- name: Check if LapRF is plugged in
  stat:
    path:  "{{ openrace.racerf_device }}"
  register: device
  tags:
     - core

- name: "Create race_core container with LapRF from {{ race_core_image }}"
  docker_container:
    name: race_core
    image: "{{ race_core_image }}"
    recreate: yes
    restart_policy: "{{ openrace.restart_policy }}"
    networks:
      - name: openrace
    volumes:
      - "/srv/openrace/log:/app/log/:rw"
      - "/srv/openrace/archive:/app/archive/:rw"
    devices:
      - "{{ openrace.racerf_device }}:{{ openrace.racerf_device }}"
    env:
      MQTT_HOST: mqtt
      MQTT_USER: openrace
      MQTT_PASS: PASSWORD
      DEBUG: false
  become: true
  when: device.stat.islnk is defined and device.stat.islnk
  tags:
     - core

- name: "Create race_core container without LapRF from {{ race_core_image }}"
  docker_container:
    name: race_core
    image: "{{ race_core_image }}"
    recreate: yes
    restart_policy: "{{ openrace.restart_policy }}"
    networks:
      - name: openrace
    volumes:
      - "/srv/openrace/log:/app/log/:rw"
      - "/srv/openrace/archive:/app/archive/:rw"
    env:
      MQTT_HOST: mqtt
      MQTT_USER: openrace
      MQTT_PASS: PASSWORD
      DEBUG: false
  become: true
  when: device.stat.islnk is not defined
  tags:
     - core
