---
- name: Create an angular-ui container
  docker_container:
    name: angular-ui
    image: angular-ui
    recreate: yes
    networks:
      - name: openrace
    ports:
      "5001:80"
    env:
      MQTT_WEBSOCKETS_HOST: mqtt:9001
  become: true
  tags:
     - ui

- name: Create OpenRace log directory
  file:
    path: /srv/openrace/log/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create OpenRace race archive directory
  file:
    path: /srv/openrace/archive/
    state: directory
    owner: pi
    group: pi
    mode: 0777
  become: true

- name: Create a led_control container
  docker_container:
    name: led_control
    image: led_control
    recreate: yes
    networks:
      - name: openrace
    volumes:
      - "/srv/openrace/log:/app/log/:rw"
    env:
      MQTT_HOST: mqtt
      MQTT_USER: openrace
      MQTT_PASS: PASSWORD
      DEBUG: false
  become: true

- name: Check if LapRF is plugged in
  stat:
    path:  "{{ racerf_device }}"
  register: device
  tags:
     - core

- name: Create a race_core container with LapRF
  docker_container:
    name: race_core
    image: race_core
    recreate: yes
    networks:
      - name: openrace
    volumes:
      - "/srv/openrace/log:/app/log/:rw"
      - "/srv/openrace/archive:/app/archive/:rw"
    devices:
      - "/dev/racetracker:/dev/racetracker"
    env:
      MQTT_HOST: mqtt
      MQTT_USER: openrace
      MQTT_PASS: PASSWORD
      DEBUG: false
  become: true
  when: device.stat.islnk is defined and device.stat.islnk
  tags:
     - core

- name: Create a race_core container without LapRF
  docker_container:
    name: race_core
    image: race_core
    recreate: yes
    networks:
      - name: openrace
    volumes:
      - "/srv/openrace/log:/app/log/:rw"
      - "/srv/openrace/archive:/app/archive/:rw"
    env:
      MQTT_HOST: mqtt
      MQTT_USER: openrace
      MQTT_PASS: PASSWORD
      DEBUG: false
  become: true
  when: device.stat.islnk is not defined
  tags:
     - core
