---
- name: configure dhcpcd
  copy:
    src: dhcpcd.conf
    dst: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: installing dnsmasq
  package:
    name: dnsmasq
    state: present
  become: true

- name: enabling dnsmasq
  service:
   name: dnsmasq
   state: enabled
  become: true

- name: configure dnsmasq
  copy:
    src: dnsmasq.conf
    dst: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  become: true

- name: installing hostapd
  package:
    name: hostapd
    state: present
  become: true

- name: enabling hostapd
  service:
   name: hostapd
   state: enabled
  become: true

- name: configure hostapd
  template:
    src: hostapd.j2
    dst: /etc/hostapd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart hostapd
  become: true

- name: confiure hostapd daemon
  lineinfile:
    dest: /etc/default/hostapd
    regexp: '^#DAEMON_CONF='
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart hostapd
  become: true

