---
- name: Create OpenRace Directory
  file:
    path: "{{ playbook_dir }}/.."
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0777
  become: true

- name: Synchronize code
  synchronize:
    src: ../../../../src
    dest: "{{ playbook_dir }}/.."
    use_ssh_args: yes
    rsync_opts:
      - "--exclude=ui"
  become: true
