---

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: true

- name: restart hostapd
  service:
    name: hostapd
    state: restarted
  become: true

- name: restart dhcpcd
  service:
    name: dhcpcd
    state: restarted
  become: true
