---

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: yes
  become: true

- name: restart hostapd
  systemd:
    name: hostapd
    state: restarted
    daemon_reload: yes
  become: true

- name: restart dhcpcd
  systemd:
    name: dhcpcd
    state: restarted
    daemon_reload: yes
  become: true
