---

# see https://github.com/docker/docker-py/issues/1502
- name: install dirty workaround for "Failed to import docker or docker-py - No module named requests.exceptions."
  package:
    name: python-backports.ssl-match-hostname
    state: present

- name: installing python 2 pip for ansible and dependencies
  package:
    name: python-pip
    state: present
  become: true

- name: install ansible docker dependency
  pip:
    name:
      - docker
      - requests>=2.20.1
    executable: pip2

- name: Create an openrace docker network
  docker_network:
    name: openrace
  become: true
  tags:
    - ui
    - mqtt
    - led
    - core
