---

- name: installing python3 pip
  package:
    name: python3-pip
    state: present
  become: true

- name: adding user pi to group dialout (for the serial connection)
  user:
    name: "{{ ansible_user_id }}"
    groups: dialout
    append: yes
  become: true


#- name: installing virtual environment and dependencies
#  pip:
#    requirements: "{{ playbook_dir }}/../requirements.txt"
#    virtualenv: "{{ playbook_dir }}/../venv"
#    virtualenv_python: python3
#- name: installing virtual environment and dependencies
#  pip:
#    requirements: "{{ playbook_dir }}/../requirements.txt"
#    virtualenv: "{{ playbook_dir }}/../venv"
#    virtualenv_python: python3
