## Ansible execution
# ansible-playbook site.yml
# --tags or --skip-tags
# depending on your setup, you need to use --ask-become-pass

## Available tags:
# start
# os
# mqtt
# ui
# led
# core

## Special options
# to enable or disable the access point of the Raspberry Pi, you can
# set the ansible variable "raspberry_ap" to true or false. The script
# ap.sh does exactly this.

### BASIC
# basic system updates, packages and settings
- hosts: all
  roles:
    - { role: python,                # setup python requirements
        tags: ['os'] }
    - { role: docker-install,        # install docker
        tags: ['os'] }
    - { role: accesspoint,           # setup system as access point only on raspberry pi
        tags: ['os', 'ap'],
        when: '"wlan0" in ansible_interfaces' }
    - { role: synchronized-code,
        when: build_images }
    - { role: build-images,
        when: build_images }
    - { role: created-openrace-network,
        tags: ['start'] }
    - { role: started-mqtt,
        tags: ['mqtt'] }
    - { role: started-openrace,
        tags: ['start'] }
    - { role: racetracker-watchdog,  # setup udev rules and watchdog
        tags: ['os'] }
