name: Publish Docker Images

on:  
  push:
    branches:
      - master

jobs:
  push-docker-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest

    - name: Build docker images
      run: |
        docker login --username ${{ secrets.dockerhub_builduser_username }} --password ${{ secrets.dockerhub_builduser_password }}
        cd ./tools
        IMAGE_VERSION="1.0.3"

        for SERVICE in race_core led_control audio_output ui
        do
            cat ../src/${SERVICE}/Dockerfile | sed '/as base/ s/FROM /FROM amd64\//g' | docker build --platform linux/amd64 -f - -t openrace/${SERVICE}:${IMAGE_VERSION}-amd64 ../src/${SERVICE}/
            docker push openrace/${SERVICE}:${IMAGE_VERSION}-amd64

            cat ../src/${SERVICE}/Dockerfile | sed '/as base/ s/FROM /FROM arm32v7\//g' | docker buildx build --platform linux/arm/v7 -f - -t openrace/${SERVICE}:${IMAGE_VERSION}-arm32v7 ../src/${SERVICE}/
            docker push openrace/${SERVICE}:${IMAGE_VERSION}-arm32v7
        done
