name: Publish Docker Images

on:  
  push:
    branches:
      - master

jobs:
  push-docker-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest

    - name: Build docker images
      run: |
        docker login --username ${{ secrets.dockerhub_builduser_username }} --password ${{ secrets.dockerhub_builduser_password }}
        cd ./tools
        export DOCKER_CLI_EXPERIMENTAL=enabled
        ./publish_docker_images.sh     

