name: Publish Docker Images

on:  
  push:
    branches:
      - master

jobs:
  push-docker-images:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest
    - uses: actions/checkout@v1
    - name: Build docker images
      run: |
        docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            --output "type=image,push=false" \
            --file ./src/audio_output/Dockerfile ./src/audio_output     

